# Generated by Django 5.0.7 on 2024-08-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='Description',
            field=models.TextField(default=''),
        ),
    ]
