# Generated by Django 5.0.7 on 2024-07-31 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Genero', '0001_initial'),
        ('Ilustracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlustracionGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='Genero.genero')),
                ('ilustracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilustracionGenero', to='Ilustracion.ilustracion')),
            ],
        ),
    ]
