# Generated by Django 5.0.7 on 2024-08-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_remove_usuario_age_remove_usuario_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telephone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
