# Generated by Django 5.0.7 on 2024-08-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comentario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
